### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by CARL-JOSEPH-LEE** [Duke486/Miku-Skin-ClashVerge#1]
![屏幕截图 2024-10-29 225236](https://github.com/user-attachments/assets/b25cb7ed-e59d-4949-86b4-a49b9d86c77d)

**Comment by Duke486** [comment]
皮肤内图片借助图床加载，可能在你的地区不适用。请把仓库里的图片存到本地或其他图床，并修改css中的图片src。

**Comment by CARL-JOSEPH-LEE** [comment]
> 皮肤内图片借助图床加载，可能在你的地区不适用。请把仓库里的图片存到本地或其他图床，并修改css中的图片src。

破案了，实际上是主题模式“深色”的原因，改成浅色就行了。

**Comment by Duke486** [comment]
> > 皮肤内图片借助图床加载，可能在你的地区不适用。请把仓库里的图片存到本地或其他图床，并修改css中的图片src。
> 
> 破案了，实际上是主题模式“深色”的原因，改成浅色就行了。

看了一下，你的Verge版本与皮肤版本不匹配，请升级软件
