### ISSUE TITLE
局部移除模糊效果

### ISSUE THREAD

**Issue by AdySnowflake** [Duke486/Miku-Skin-ClashVerge#3]
（感觉这个内容放在discussion会更好）
如果有人喜欢看miku的小腿，那么可以局部移除模糊效果。
```
.MuiBox-root.css-79elbk {
    background-color: rgba(255, 255, 255, 0) !important;
    backdrop-filter: none; /* 移除模糊效果 */
}
```
将这一段代码添加在**MuiBox-root**下方即可。
对比效果：
![98a4a6c0ac918ca37b02b6ed55cad362](https://github.com/user-attachments/assets/4fad618c-de78-4187-b2a1-fc296ec806d0)

![PixPin_2024-11-29_12-10-01](https://github.com/user-attachments/assets/2d57dbea-622d-4ab9-bb84-2532f675a746)
其他地方修改效果也是类似的方法。

**Comment by Duke486** [comment]
感谢建议，如果可以请您提出PR😊

**Comment by AdySnowflake** [comment]
> 感谢建议，如果可以请您提出PR😊

您好！ 已经提交PR了。感谢大佬给我提交pr的机会，第一次操作不太熟练。

**Comment by Duke486** [comment]
谢谢你的建议

**Comment by Duke486** [comment]
@AdySnowflake 
Miku-Skin-ClashVerge 项目接手邀请
你好：
我是 Miku-Skin-ClashVerge 的仓库所有者 Duke486，感谢你之前为项目提交改进。
因个人工作安排，我计划退出项目维护，并在完成交接后删除自己名下的仓库。我希望这个项目能继续留在 GitHub，供喜欢这款皮肤的用户使用，因此想问问你是否愿意接手。
我的想法是：由你在自己的账号或组织下，以 Miku-Skin-ClashVerge 原名重新公开发布，并负责后续维护。交接后，我不再担任仓库所有者或维护者，后续更新节奏和发展方向由你决定。
无论是否方便接手，都感谢你之前对项目的帮助，没有压力。
期待你的回复。
Duke486

**Comment by AdySnowflake** [comment]
你好，可以直接把我添加为collaborater。
如果一定要删除仓库的话，可以transfer给我。
我之前建立过仓库，在提交某个pr的时候。但是这样的效果并不好，因为皮肤随cvr大版本更新，用户基本不会打开仓库查看动向，也难以得知有新仓库。

Duke486 ***@***.***> 于 2026年9月22日周二 19:51写道：
